apiVersion: v1
kind: Service
metadata:
  name: betterdata-admin
  namespace: betterdata
  labels:
    app.kubernetes.io/name: betterdata-admin
    app.kubernetes.io/part-of: betterdata
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: betterdata-admin
  ports:
    - name: http
      port: 3001
      targetPort: http
