apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - web-deployment.yaml
  - web-service.yaml
  - admin-deployment.yaml
  - admin-service.yaml
  - api-deployment.yaml
  - api-service.yaml
  - worker-deployment.yaml
  - worker-scaledobject.yaml
  - payment-retry-cronjob.yaml
  - cloudflared-deployment.yaml
